### ISSUE TITLE
Add refined module

### ISSUE THREAD

**Issue by alexarchambault** [travisbrown/circe#101]
@fthomas's [refined](https://github.com/fthomas/refined) allows to restrict the values that some fields can take, at the type level, like
```scala
case class SimpleT(
  i: Int @@ Positive,
  s: String @@ NonEmpty,
  l: List[Int] @@ Size[Greater[_3]]
)
```
preventing before hand the corresponding fields to have invalid values.

I added a [module](https://github.com/alexarchambault/argonaut-shapeless/tree/master/refined/) with codecs for that in argonaut-shapeless, that works nicely too.

Just wanted to enquire opinions, before possibly sending a PR here, with a module for that.

**Comment by travisbrown** [comment]
:+1: from me.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/travisbrown/circe/pull/103
