### ISSUE TITLE
Change the name?

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#11]
jfc was my working title when I started the project a couple of weeks ago. Arguments against it include the following:

1. It's hard to search for.
2. The acronym happens to coincide with a profane bit of Internet slang.
3. Nobody ever, ever wants to be confused with the Java Foundation Classes.

I still like it. I prefer package names to be reverse domain names owned by the project developers (I get annoyed every time I have to write e.g. `import _root_.argonaut._` because of an `argonaut` subpackage somewhere). `io.jfc` is unambiguous in that respect and short enough that writing out the fully-qualified name isn't too much of a burden.

@non's "circe" is the best alternative candidate I've heard so far, but I'm happy to consider others.

**Comment by non** [comment]
Just to document it here, Circe was a goddess of magic in Greek mythology, and had a role in purifying the Argonauts: https://en.wikipedia.org/wiki/Circe#Later_Greek_literature

**Comment by tpolecat** [comment]
Love it, specifically because of (2) above. I'm a fan of edgy names :-)

**Comment by tlockney** [comment]
The name is also what you might expect people to post on Twitter when they see that there's yet another Scala JSON library. E.g., "jfc yet another JSON library?!? What the hell is this @travisbrown guy thinking??? https://github.com/travisbrown/jfc" ;~)

**Comment by vkostyukov** [comment]
+1 for "jfc". It's a great name for this project. Especially when used with project description: " jfc, yet another JSON library" :)

**Comment by InTheNow** [comment]
Jason And the Argonauts -> "Jaguar". They even have a Golden "Fleece"

**Comment by ceedubs** [comment]
I like circe (though I think there should be a pronunciation helper near the top of the README).

I like "edgy" names to some extent. It makes me very happy that Verizon is using a library called Doobie. However, "jfc" is a term that many would find offensive. Whatever your or my thoughts on religion, it means a great deal to many people, and I think that should be respected.

And on a more practical note, I do agree with @InTheNow's suggestion that the name "jfc" could likely come back to haunt - most likely as a GitHub issue or pull request that derails.

**Comment by InTheNow** [comment]
@travisbrown Just to be clear - I personally don't have an issue with "jfc", I just don't want to see your work go to waste over a name.

I do like "Doobie".... how about "Scoobie"? :wink:

**Comment by tpolecat** [comment]
Ok re: fleece + cats the correct name is **fleas**. You're welcome.

**Comment by travisbrown** [comment]
Thanks for the input, all. I'm thinking we probably should change the name, and sorry, @tpolecat but "circe" is still the current frontrunner. I'm planning an 0.1 for this coming weekend, and any name change will happen before then, but other suggestions are still definitely welcome.

**Comment by mdedetrich** [comment]
How about "meowson" play on "meow" + "json" (meow coming from cats)

**Comment by trane** [comment]
*cough* purrgonaut *cough*

**Comment by mdedetrich** [comment]
Oh my god, purrgonaut is so good

**Comment by milessabin** [comment]
Someone _has_ to find a good use for "fleas" ;-)

**Comment by seanparsons** [comment]
@non "...had a role in purifying the Argonauts..." Indeed.

**Comment by travisbrown** [comment]
@seanparsons For the record, I like the name "circe" because it's vaguely associated with Jason and the Argonauts, but mostly I just think that a person whose biggest claim to fame is turning people into animals is a good figurehead for a library about turning Scala types into a horrible format like JSON.

I mean [what I say](https://github.com/travisbrown/circe#why) about Argonaut in the README—I like both it and Scalaz, I'm sure I'll be using both for a long time, and if I find [bugs](https://github.com/argonaut-io/argonaut/pull/188) in code from Argonaut or run into ideas that I think would fit well there, I'll definitely continue to contribute them back.
