### ISSUE TITLE
Request for Case Class Example for De(serialization) 

### ISSUE THREAD

**Issue by kevinmeredith** [travisbrown/circe#130]
In my experience with the Play and spray JSON libraries, there's usually a way to serialize and de-serialize using `case classes`

Example from spray-json:

```
import spray.json._

case class Boy(name: String, hobbies: List[String]) extends Parent
```

A `Formatter` provides de-serialization and serialization:

```
object Boy {
    import spray.json.DefaultJsonProtocol._

    implicit val format: RootJsonFormat[Boy] = 
        jsonFormat2(Boy.apply)
}
```

Does such capability exist in `circe`? If so, could you please show me an example? And, if there is such a way to do this, perhaps it'd be worthwhile to add to the README?

**Comment by travisbrown** [comment]
Does the example in the [quick start](https://github.com/travisbrown/circe#quick-start) count? If you import `io.circe.generic.auto` you get fully automatic codec derivation for case classes (assuming there are codecs for all members). There's no need to define instances manually, unless you need more control over _how_ the case classes are represented.

**Comment by kevinmeredith** [comment]
Ah - I completely missed that example.

Thank you, Travis!

**Comment by kevinmeredith** [comment]
As a follow-up question, that example decodes JSON to a `Foo`, which is a sealed trait.

`scala> decode[Foo](foo.asJson.spaces4)`

Since `Foo` could be either a `Bar` or a `Qux`, how are you defining that decoder?

*Aside* - my reason for asking - https://www.reddit.com/r/scala/comments/3ual3j/proper_deserialization_of_a_trait/

**Comment by travisbrown** [comment]
There are a [few possible ways](https://gitter.im/travisbrown/circe?at=5640c1ee2e8c19094ec0f714) to represent sealed trait hierarchies, and the default generic derivation uses a wrapper object with a single field with the constructor name as the key (for reasons discussed [here](https://gitter.im/travisbrown/circe?at=5646324e5b7a2ea84f0817d9)).

So in the quick start you get this:

```scala
scala> val foo: Foo = Qux(13, Some(14.0))
foo: Foo = Qux(13,Some(14.0))

scala> foo.asJson.noSpaces
res0: String = {"Qux":{"d":14.0,"i":13}}
```

The result could also be something like this:

```scala
scala> foo.asJson.noSpaces
res0: String = {"d":14.0,"i":13,"type":"Qux"}
```

Or just this:

```scala
scala> foo.asJson.noSpaces
res0: String = {"d":14.0,"i":13}
```

But both of those approaches have painful edge cases that the first doesn't.
