### ISSUE TITLE
Add a deep merge operation

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#169]
Requested by @mpilquist on Gitter, where there's [some discussion](https://gitter.im/travisbrown/circe?at=56915002ee13050b38a293b3) of the issues involved. For now I think it makes sense to go with something like the simpler version in Argonaut (not the `HCursor => HCursor` idea) but with the argument determining the field order for consistency.

**Comment by anakos** [comment]
As per the contributing guide, I am going to begin work on this.

**Comment by travisbrown** [comment]
Fixed by @anakos in #172.
