### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by Mullefa** [travisbrown/circe#209]
In the first example, should import `io.circe.parse._` (not `io.circe.parser._`).

**Comment by travisbrown** [comment]
@Mullefa The name of the package was changed in 0.3.0 (see #184). I guess we could note that in the README, but given the fact that the project is so young I'd prefer to encourage people to upgrade as quickly as possible.

**Comment by Mullefa** [comment]
Ah, I see. Sorry bout that. Will update regularly moving forward.
