### ISSUE TITLE
Compiling large case class randomly fails

### ISSUE THREAD

**Issue by cin** [travisbrown/circe#238]
I am having issues compiling a large case class with circe. The case class has 48 parameters and randomly fails to compile with the following error:

could not find implicit value for parameter d: io.circe.Decoder[foo]

Any ideas what may be going on? I actually need to add more elements to the case class but this seems to be the tipping point.

**Comment by djx314** [comment]
Have any DateTime, Timestamp, Date fields?

**Comment by cin** [comment]
No, all base types. I actually got it to compile a few times in a row by explicitly deriving the decoder.

i.e.
private implicit val myDecoder: Decoder[foo] = deriveDecoder[foo]

However, if I add just one more element to the case class it fails to compile with:
could not find implicit value for parameter decode: shapeless.Lazy[io.circe.generic.decoding.DerivedDecoder[foo]]

So strange...

**Comment by djx314** [comment]
Will it compile successfully with circe 0.4.0(include shapeless 2.3.0 with the bug fix)?
The best way is provide your case class with all the fields renamed and call travisbrown.

**Comment by cin** [comment]
I just built from master (0.4.0-SNAPSHOT) and got a similar error:
could not find Lazy implicit value of type io.circe.generic.decoding.DerivedDecoder[foo]

It would then work once I took off a few parameters.

I think I can work around this issue by breaking the case class up (like you'd have to do pre-scala 2.10). It's just a weird problem.

**Comment by travisbrown** [comment]
There's some discussion of this kind of problem in the [warnings section](https://github.com/travisbrown/circe#warnings-and-known-issues) of the README. You can try `-J-Xss64m`, but it won't always work—the parts of the compiler that Shapeless and circe rely on just aren't up to large-ish case classes.

Manually defined instances (or code-gen-ed ones) may be your best option, unfortunately.

**Comment by cin** [comment]
@travisbrown that seems to work consistently. Thanks! Sorry, I saw that bullet note the first time through and misinterpreted it. I haven't tried to add any more variables to the case class, but I don't see why that would be an issue in this case (no sealed traits). Thanks to @djx314 for helping out with issue as well! :)
