### ISSUE TITLE
Inconsistent PrettyPrinting

### ISSUE THREAD

**Issue by dk14** [travisbrown/circe#270]
```
scala> val rawJson = """{"hello": "world", "age": 42, "nested": { "deeper": { "treasure": true }}}"""
rawJson: String = {"hello": "world", "age": 42, "nested": { "deeper": { "treasure": true }}}

scala> rawJson.asJson.noSpaces
res24: String = "{\"hello\": \"world\", \"age\": 42, \"nested\": { \"deeper\": { \"treasure\": true }}}"

scala> decode[HelloWorld](rawJson).map(_.asJson.noSpaces).getOrElse("")
res25: String = {"hello":"world","age":42,"nested":{"deeper":{"treasure":true}}}
```

res24 is not parsable because of "\\"

**Comment by djx314** [comment]
I think it's not a bug. res24 is a simple json string. Not a json object.

**Comment by knutwalker** [comment]
`rawJson.asJson` does not parse the rawJson string into the AST, it creates a single JsonString value that has `rawJson` as its content, hence the escaping. You have to use `decode` or `parse` to get the Json AST.

```scala
@ import io.circe._
@ import io.circe.parser._
@ import cats.data.Xor

@ val rawJson = """{"hello": "world", "age": 42, "nested": { "deeper": { "treasure": true }}}"""
rawJson: String = """
{"hello": "world", "age": 42, "nested": { "deeper": { "treasure": true }}}
"""
@ val Xor.Right(json) = decode[Json](rawJson)
json: Json = {
  "hello" : "world",
  "age" : 42,
  "nested" : {
    "deeper" : {
      "treasure" : true
    }
  }
}
@ json.noSpaces
res7: String = """
{"hello":"world","age":42,"nested":{"deeper":{"treasure":true}}}
"""
```

**Comment by dk14** [comment]
By res24 isn't parsable I meant this:

```
scala> decode[HelloWorld](res24)
res32: cats.data.Xor[io.circe.Error,HelloWorld] = Left(DecodingFailure(Attempt to decode value on failed cursor, List(El(DownField(hello),false,true))))
```

**Comment by knutwalker** [comment]
This is because `res24` isn't a string that contains json object, it is a string rendering of a json *string*. I don't think `rawJson.asJson` produces what you want.

**Comment by dk14** [comment]
So how can I parse rendered json string? Or more precisely, why that rendered string contains `\\` (escaped backslash)?

I disagree about `asJson`. You can clearly see that it returns `io.circe.Json` which is AST

**Comment by djx314** [comment]
<https://github.com/travisbrown/circe#transforming-json>

**Comment by dk14** [comment]
```
scala> Decoder[HelloWorld].apply(parse(res24).getOrElse(Null).hcursor)
res58: io.circe.Decoder.Result[HelloWorld] = Left(DecodingFailure(Attempt to decode value on failed cursor, List(El(DownField(hello),false,true))))
```

And second question is still in place: why nospaces (and other pretty printers) puts "\\" in one case and doesn't do it in the other one. It's the same `nosapces`. I didn't explicitly ask for '\\` - I don't even know why would I need it (as this is not actual escaping - like `\"` - it's `\\"`).

**Comment by dk14** [comment]
To be more precise. I can "parse" `res24`, but I still can't decode it to a `case class`.
And I actually can't work with it:

```
scala> parse(res24).getOrElse(Null).hcursor.downField("hello").withFocus(_.mapString(_.reverse)).top
res61: Option[io.circe.Json] = None
```
 

Compare to `res25`:

```
scala> parse(res25).getOrElse(Null).hcursor.downField("hello").withFocus(_.mapString(_.reverse)).top
res62: Option[io.circe.Json] =
Some({
  "hello" : "dlrow",
  "age" : 42,
  "nested" : {
    "deeper" : {
      "treasure" : true
    }
  }
})

```

**Comment by knutwalker** [comment]
There are two ways to get to a Json AST. The first is from a serialized/wire representation, such as a string by means of parsing. The second is from your domain types and entities by means of encoding.
There are also two ways to go from the Json AST, one is to the serialized/wire representation by means of (pretty-)printing, the other is by means of decoding. `asJson` is only for the second way, so it treats your `rawJson` in the same way it would do with `HelloWorld` or other case class. The resulting AST ist a single JsonString containing complete `rawJson`, not a JsonObject. The printer (`spaces2` in `toString` or the explicit `noSpaces`) is then rendering this Json AST, the single JsonString as a string. That means, if you *parse* the result (`res24`), you would only get a String back, not a case class. What you want is *parse* the *rawJson*, not the res24. This step will give you the Json AST that you can use to decode into your case class.

**Comment by dk14** [comment]
Ok, now I understand, sorry for trying to force it as a bug :).

As I understand, you've meant not getting a Json String back - you mean I'll get a `io.circe.Json.String` back. I just didn't read it careful enough.

It actually a common misunderstanding - I was trying to make this example work, as the author claimed that it doesn't: http://manuel.bernhardt.io/2015/11/06/a-quick-tour-of-json-libraries-in-scala/. I believe the author faced the same problem.

Maybe you should add more examples to README.

Thanks, and sorry again :)
