### ISSUE TITLE
Semi-auto génération doesn't handle collections

### ISSUE THREAD

**Issue by edmondo1984** [travisbrown/circe#286]
The following snippet fails to compile with circe 0.4.1

case class SomeClass1(prop1:String, prop2:String)

 

case class SomeClass2(prop:String)

 

case class SomeClass2Detail(blah:Int)

 

case class Aggregate(prop:SomeClass1, stuff:List[SomeClass2], details:Map[SomeClass2,SomeClass2Detail])

 
```scala
class CirceProblem {

  import io.circe.generic.semiauto._

  import io.circe.syntax._

  import io.circe._

 

  val dec1 = deriveDecoder[SomeClass1]

 

  val dec2 = deriveDecoder[SomeClass2]

 

  val dec3 = deriveDecoder[SomeClass2Detail]

 

  val dec4 = deriveDecoder[Aggregate]

}
```

**Comment by travisbrown** [comment]
Not at a computer at the moment, but take a look at the `KeyDecoder` section in the 0.4.0 release notes—I think that's all you're missing.

**Comment by travisbrown** [comment]
@edmondo1984 Did you get this figured out? If you have a `KeyDecoder` instance like this for `SomeClass1` this derivation should "just work":
```scala
implicit val decodeKeySomeClass1: KeyDecoder[SomeClass1] =
  KeyDecoder[String].map(SomeClass1(_))
```

**Comment by edmondo1984** [comment]
I did thanks so much

**Comment by travisbrown** [comment]
Great, thanks!
