### ISSUE TITLE
Automatic encoders fail when compiling with -Yno-predef

### ISSUE THREAD

**Issue by cmiller-wikia** [travisbrown/circe#298]
Decoders, however work fine. 

Work-around is importing Predef.ArrowAssoc wherever you need the encoder implicit to be available.

```
scala> import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._
import io.circe._
import io.circe.generic.auto._
import io.circe.parser._
import io.circe.syntax._

scala> case class Foo(s: String)
defined class Foo

scala> val dec = Decoder[Foo]
dec: io.circe.Decoder[Foo] = io.circe.generic.decoding.DerivedDecoder$$anon$1@7be4f5bf

scala> val enc = Encoder[Foo]
<console>:25: error: could not find implicit value for parameter instance: io.circe.Encoder[Foo]
       val enc = Encoder[Foo]
                        ^

scala> import Predef.ArrowAssoc
import Predef.ArrowAssoc

scala> val enc = Encoder[Foo]
enc: io.circe.Encoder[Foo] = io.circe.generic.encoding.DerivedObjectEncoder$$anon$1@3e6b2787
```

**Comment by fthomas** [comment]
I'm guessing this is because `->` in this [quasiquote](https://github.com/travisbrown/circe/blob/f1822b0877b77798fc5edd130bd9b5dd99e9b348/generic/shared/src/main/scala/io/circe/generic/DerivationMacros.scala#L216) is not fully qualified.

**Comment by travisbrown** [comment]
@cmiller-wikia @fthomas Good catch—will get this fixed asap.

**Comment by sideeffffect** [comment]
I'm witnessing what seems to be exactly this issue (implicit `Encoder` not being found when `-Yno-predef`) in `0.10.1`

it might be important that in my case my case class contains an `immutable.Seq` (not `Seq`)

@travisbrown could you please reopen this ticket? what other info would help you to fix this problem?
