### ISSUE TITLE
Use export-hook in core

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#30]
I'm creating this issue to follow up on a comment by @dwijnand [on gitter](https://gitter.im/travisbrown/circe?at=55cb4fe20c29567545d9d7c0):

> The only thought I had about #29 is the need for the imports, and I that made me think if maybe core should use export-hook

I've played around with [export-hook](https://github.com/milessabin/export-hook) in core, but I really want to push on the experiment of keeping generic derivation modular for as long as possible. I don't love my current approach of getting priorities right by balancing a tower of instance-providing traits and using a `Secondary` wrapper, but it seems to work reasonably well, and is still (I think) not completely unintelligible.

**Comment by travisbrown** [comment]
I'm removing the question tag since @milessabin has just convinced me that export-hook can do what I want. I'll tackle this next week unless someone beats me to it.

**Comment by travisbrown** [comment]
Fixed by #43.

**Comment by travisbrown** [comment]
Fixed by #43.

**Comment by dwijnand** [comment]
:+1:
