### ISSUE TITLE
Publish artifacts for Scala 2.12

### ISSUE THREAD

**Issue by tindzk** [travisbrown/circe#302]
I am in the process of cross-compiling some of my libraries for Scala 2.12. Would it be possible to publish Circe's artifacts for 2.12?

**Comment by travisbrown** [comment]
Unfortunately Cats is not yet published for 2.12 (if I remember correctly this is primarily an issue with test library versions). As soon as that's out I'll publish 2.12 artifacts for circe.

**Comment by tindzk** [comment]
Great, thanks!

**Comment by SethTisue** [comment]
ticket on the availability of Cats for 2.12: https://github.com/typelevel/cats/issues/1285

**Comment by travisbrown** [comment]
@tindzk I've got #417 lined up and ready to go as soon as Cats 0.8.0 is published, and if you really wanted you could build that branch locally now after publishing [this Cats branch](https://github.com/typelevel/cats/pull/1415) (which should get merged today, I hope) locally.

**Comment by tindzk** [comment]
That's great news! Thanks a lot.

**Comment by SethTisue** [comment]
Cats 0.8.0 is published

**Comment by travisbrown** [comment]
@SethTisue Yep. I got bogged down with a couple of iteratee.io changes yesterday, but the circe release will be out today.

**Comment by martinring** [comment]
Would be great to see 0.6.0-RC1 for 2.12 final!

**Comment by SethTisue** [comment]
it appears to me that 0.6.0 was published for 2.12 and this ticket can be closed?

**Comment by travisbrown** [comment]
@SethTisue Yep, thanks.
