### ISSUE TITLE
Json number equality for zero

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#348]
Thanks to @davegurnell for identifying this issue on Java 7:

```scala
scala> import io.circe.Encoder, io.circe.jawn.parse
import io.circe.Encoder
import io.circe.jawn.parse

scala> Encoder[Double].apply(0.0) == parse("0.0").toOption.get
res0: Boolean = false
```

The equality logic in `BiggerDecimal` is correct, but we're running into [this JDK bug](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6480539), which is fixed in Java 8. The bug affects both Oracle and OpenJDK.

This is bad enough that I think we need to work around the JDK bug for as long as we're supporting Java 7. I'll plan to have the fix ready for the 0.5.0 release, but won't plan to backport to 0.4.x unless someone has a particular need for it.

**Comment by davegurnell** [comment]
Nice sleuthing! I had no idea the issue was that specific!
