### ISSUE TITLE
How to create encoders and decoders for non-case classes?

### ISSUE THREAD

**Issue by danielyli** [travisbrown/circe#350]
I'm having a bit of trouble writing an encoder/decoder pair for a class that I don't control and that's not a case class.  For the following example, I'll use `java.time.Instant`.

Looking at [Circe's source](https://github.com/travisbrown/circe/blob/master/core/shared/src/main/scala/io/circe/Encoder.scala#L204), writing the encoder is straightforward:

    import java.time.Instant
    import io.circe._, io.circe.generic.auto._, io.circe.parser._, io.circe.syntax._

    implicit val encodeInstant = new Encoder[Instant] {
      final def apply(a: Instant): Json = Json.fromString(a.toString)
    }

It's the decoder that's the problem.  Following the example set by [Circe's source](https://github.com/travisbrown/circe/blob/master/core/shared/src/main/scala/io/circe/Decoder.scala#L558):

    type Result[A] = Xor[DecodingFailure, A]

    implicit val decodeInstant = new Decoder[Instant] {
      final def apply(c: HCursor): Result[Instant] = c.focus match {
        case JString(string) => try {    // error: not found: value JString
          Xor.right(Instant.parse(string))
        } catch {
          case _: Throwable => Xor.left(DecodingFailure("Instant", c.history))
        }
        case _ => Xor.left(DecodingFailure("Instant", c.history))
      }
    }

The problem is that `JString` is private to Circe.  If using `JString` isn't the way to go, what's the canonical way of writing a custom decoder?

**Comment by bthuillier** [comment]
with circe you can directly use primitive decoder/encoder
```scala
// Decoder
Decoder.decodeString.emap { str =>
    Xor.catchNonFatal(Instant.parse(str)).leftMap(t => "Instant")
  }

// Encoder
Encoder.encodeString.contramap[Instant](i => i.toString)
```

**Comment by danielyli** [comment]
Thank you!

This seems like a common use case.  May I suggest it be put in the Readme, under the Usage section?

**Comment by bthuillier** [comment]
It can be a good idea, any thought @travisbrown ?
