### ISSUE TITLE
Codecs for maps with non-string keys

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#38]
@koshelev asked today [on gitter](https://gitter.im/travisbrown/circe?at=55d4d70a11c7afc249785e77) about `Decoder` instances for a `Map` with non-string keys.

It'd be nice to have a clear story for these cases. This new [Argonaut pull request](https://github.com/argonaut-io/argonaut/pull/189/files) by @xuwei-k is one solution: you have to provide a mapping from keys to strings, and then you get the instance for free. Alternatively uPickle provides `Map[NonString, Bar]` instances that serialize to JSON arrays of pairs.

I'm leaning toward not providing instances for maps with non-string keys by default (for the reason given [here](https://gitter.im/travisbrown/circe?at=55d4ee971ba62e4a21fa72b2)), but making it easy for users to define uPickle-style instances if they want them.

**Comment by koshelev** [comment]
I like the first approach, with mapping keys to string. It could be very handy in case where a key is a scala value class, wrapping strings.

**Comment by ngbinh** [comment]
Yes, 1st approach sounds nice and easy! :)

**Comment by travisbrown** [comment]
Okay, sounds like people want this, so if someone wants to port the Argonaut implementation (with appropriate attribution), I'd be happy to merge it.

**Comment by lukewyman** [comment]
@travisbrown, I'd like to take a crack at this.

**Comment by travisbrown** [comment]
@lukewyman Oh, this is now done—I wrapped up some work that @pjan started today. Thanks, and sorry for the confusion—I should have closed the issue this morning.
