### ISSUE TITLE
Is this a bug? deriveDecoder, decodeOption, map and accumulating (!) not playing nice together

### ISSUE THREAD

**Issue by chwthewke** [travisbrown/circe#388]
Hello,

With Circe 0.5.2, I'm trying to decode a class with an optional field while wrapping its `Option` value in a data type, such as `WrappedOptionalField` here:

    case class WrappedOptionalField( f : Opt )
    
    object WrappedOptionalField {
      implicit val decode : Decoder[WrappedOptionalField] = deriveDecoder
    }

    case class Opt( value : String )
    
    object Opt {
      implicit val decoder : Decoder[Opt] = Decoder[Option[String]].map( _.fold( Opt( "" ) )( Opt.apply ) )
    }

My issue is that I'm getting an error (`Invalid`) with `decodeAccumulating` while `decode` succeeds.

At first glance, this is due to map lacking a `tryDecodeAccumulating` override, and thus `Decoder`'s default `tryDecodeAccumulating` forcibly fails on an invalid cursor before `withReattempt` (from `decodeOption`) can recover. `tryDecodeAccumulating` is presumably called on the `map`ped decoder from the macro-generated decoder (phew!)

What do you think ? Is this indeed a bug ? 

I'll try to follow-up with a PR for this, but I might not have the time for the next week or two.

TIA

**Comment by travisbrown** [comment]
Thanks @chwthewke! Yes, this is a bug, and your diagnosis is exactly right—adding a `tryDecodeAccumulating` definition fixes the issue. I'm taking a look at other places we might need this and will get a fix in today.

**Comment by chwthewke** [comment]
Awesome :)

**Comment by travisbrown** [comment]
Okay, I've got a fix in #389. I'll backport to 0.5.x after I figure out what the situation with #386 is.

**Comment by chwthewke** [comment]
Thank you @travisbrown !
