### ISSUE TITLE
Monocle lenses for Circe

### ISSUE THREAD

**Issue by adelbertc** [travisbrown/circe#39]
Dependent on: https://github.com/julien-truffaut/Monocle/issues/235

**Comment by travisbrown** [comment]
I'd love to see this happen and would happily add a circe-lenses module once Monocle's ready.

**Comment by travisbrown** [comment]
Marking this _in progress_ since I've started on it in #78 (which currently requires both cats and Scalaz).

**Comment by travisbrown** [comment]
#78 is now merged and `circe-optics` is available in the 0.3.0 snapshot.
