### ISSUE TITLE
Support for MetaRx / Widok

### ISSUE THREAD

**Issue by mkotsbak** [travisbrown/circe#41]
Would be nice if support for https://github.com/MetaStack-pl/MetaRx was added. As it probably adds a dependency, it should probably be placed in a separate module.

**Comment by travisbrown** [comment]
@mkotsbak I'm not very familiar with MetaRx—what do you imagine this support looking like?

**Comment by zarthross** [comment]
@mkotsbak this would be the responsibility of MetaRx or a 3rd party library to implement, not Circe.

**Comment by mkotsbak** [comment]
Yes, it probably should be done inside MetaRx, as done for uPickle: https://github.com/MetaStack-pl/MetaRx/commit/d5beeb614e8df7679312d1a3068a1fefddd4b772

I opened issue https://github.com/MetaStack-pl/MetaRx/issues/58 for this.
