### ISSUE TITLE
Provide parsing and printing for Scala.js

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#44]
We now have Scala.js support, but it's not terribly useful yet, since we don't have parsers or printers that work for Scala.js.

For parsing I'm thinking we'll create a new circe-js module with something like [upickle's parser](https://github.com/lihaoyi/upickle-pprint/blob/master/upickle/js/src/main/scala/upickle/json/package.scala).

For printing the only issue is that I'm using Java's `CopyOnWriteArrayList` for memoization. This was an attempt to optimize that was at least kind of successful according to [my initial benchmarks](https://github.com/travisbrown/circe#performance). It wouldn't be too hard to factor out the memoization part and provide different implementations for JS and JVM.

**Comment by alexarchambault** [comment]
About the circe-js module, would it be convenient at the end for users to write things targetting both JVM and JS?

By that, I mean that ideally, user code should be the same for both JVM and JS. To achieve that, a parser modules having a common API on both JVM and JS would be needed, backed by jawn on the JVM and native or custom parsing on JS. It could be a circe-parser module, depending on circe-jawn on the JVM, and circe-js on JS.

**Comment by alexarchambault** [comment]
About circe-js, wouldn't it be better to have both native and hand-written parsers?

**Comment by travisbrown** [comment]
circe-parser sounds reasonable to me.

What do you mean by both native and hand-written?

**Comment by alexarchambault** [comment]
Oops, I though you initially meant a parser like the one pointed at [here](https://github.com/travisbrown/circe/pull/33#issuecomment-131554727), which was what I mean by hand-written parser.

Native parser would be one backed by `JSON.parse`, which is what you meant it seems. Just a native parser like this is fine, no absolute need for a hand-written one.
