### ISSUE TITLE
Odd incorrect encoding of heterogenous map

### ISSUE THREAD

**Issue by tylerprete** [travisbrown/circe#55]
With circe 0.1.1, I'm running the following program:

```
import io.circe._
import io.circe.generic.auto._
import io.circe.jawn._
import io.circe.syntax._

object Main {
  def main(args: Array[String]) {
    val funnyMap1 = Map("a" -> Map("str" -> "b", "map" -> Map("d" -> 1)))
    val weirdJs1 = funnyMap1.asJson.noSpaces 

    println(weirdJs1)
  }
}
```

With the result:
```
{"a":{"str":{},"map":{}}}
```

**Comment by alexarchambault** [comment]
Seems related to https://github.com/milessabin/shapeless/issues/453. The second map (`Map("str" -> "b", "map" -> Map("d" -> 1))`) is inferred as `Map[String, Object]`, and `Object` happens to have a (defective) `Generic` because of https://github.com/milessabin/shapeless/issues/453.

**Comment by travisbrown** [comment]
Thanks for catching this, @tylerprete! That definitely shouldn't compile, and I've created #57 to track new tests that will verify that.
