### ISSUE TITLE
Derivation of big case class

### ISSUE THREAD

**Issue by crakjie** [travisbrown/circe#69]
Derivation of big case class finish by a `could not find implicit value for parameter e: io.circe.Encoder[A]`and `could not find implicit value for parameter e: io.circe.Decoder[A]`

[Here a gist that show the problem ](https://gist.github.com/crakjie/92138a2c685fb544cc28)

**Comment by Taig** [comment]
I am facing the same issue with way smaller case classes that are, however, deeply nested (like 5-6 levels deep). Gradually commenting some of the fields out, then compiling, and finally reenabling commented lines to compile again will eventually lead to a working build, but a clean build always fails with the missing Encoder/Decoder error. This issue keeps me from actually using circe.

**Comment by alexarchambault** [comment]
FYI, the example in the gist above is fine with [argonaut-shapeless](https://github.com/alexarchambault/argonaut-shapeless). There has to be a way to have this working here...
