### ISSUE TITLE
Reconsider integral decoders

### ISSUE THREAD

**Issue by travisbrown** [travisbrown/circe#83]
circe currently follows Argonaut in truncating, etc. when decoding integral types:

```scala
scala> io.circe.parse.decode[Short]("0.1")
res0: cats.data.Xor[io.circe.Error,Short] = Right(0)

scala> io.circe.parse.decode[Short]("123456")
res1: cats.data.Xor[io.circe.Error,Short] = Right(32767)
```

I don't really like this, and would prefer both of the above to result in failures. Any objections?

**Comment by ceedubs** [comment]
@travisbrown I agree. What about `io.circe.parse.decode[Short]("1.0")`?

**Comment by travisbrown** [comment]
@ceedubs I'd prefer to have it fail, but I think that's a case where we may need to be flexible because of real-world JSON usage. What do you think?

**Comment by julienrf** [comment]
I agree.

**Comment by ceedubs** [comment]
@travisbrown I think the "1.0" example should probably be supported. It's one of those things where you don't really care until for some reason you are getting JSON of this form and it's a hassle if your JSON lib chokes on it. So would the rule be that there can be trailing zeros after the decimal place but any other numbers would cause `Short`, `Int`, or `Long` parsing to fail?

BTW I also don't feel super strongly about this. Luckily circe makes it very easy to customize decoders, so one could work around whatever you make the default.
