### ISSUE TITLE
New module for  scala.js specific helpers

### ISSUE THREAD

**Issue by chandu0101** [travisbrown/circe#93]
as discussed in gitter 

> We can definitely add a JS-specific module that would provide convertJson, etc.—it's just not been a priority for me yet

what can be the name for new module ? 

my picks  - `sjs` , `sjs-helpers` ( just popping whats on top of my head )

**Comment by travisbrown** [comment]
My vote is for `scalajs`, with `circe-scalajs` for the artifact name. Any chance you want to get started on one? :smile:

**Comment by chandu0101** [comment]
>My vote is for scalajs, with circe-scalajs for the artifact name

:+1: 

>Any chance you want to get started on one?

I'll give a shot next week :)

**Comment by travisbrown** [comment]
Resolved in #126.
