### ISSUE TITLE
derivation not work againts scala 2.10

### ISSUE THREAD

**Issue by jilen** [travisbrown/circe#94]
It will complain 
> could not find implicit value for parameter e: io.circe.Encoder[XXX]

Code: https://github.com/jilen/play-circe/blob/master/src/test/scala/play/api/libs/circe/CirceController.scala
Repo:  https://github.com/jilen/play-circe
Build: https://travis-ci.org/jilen/play-circe/builds/89882209

**Comment by alexarchambault** [comment]
@jilen You should add the macro-paradise plugin to your build in 2.10, like described [here](https://github.com/milessabin/shapeless#shapeless-225).

The circe documentation should mention that, imo.

**Comment by jilen** [comment]
@alexarchambault  Thanks
